[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
edict-provider-schema = { path = "../crates/edict-provider-schema" }
edict-syntax = { path = "../crates/edict-syntax" }
regex = "1"
serde_json = "1"
sha2 = "0.10.9"
wasm-encoder = "=0.251.0"
wit-component = "=0.251.0"
wit-parser = { version = "=0.251.0", default-features = false, features = ["std"] }
wat = "=1.251.0"
