[workspace]
members = ["lowerer", "verifier"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.94"
license = "Apache-2.0"

[workspace.dependencies]
wit-bindgen = { version = "=0.58.0", default-features = false, features = ["macros", "realloc"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
